import { assertEquals } from "@std/assert";
import { Board, Game, Piece, test } from "./game.ts";

Deno.test(function othelloTest() {
  const finalState = test();
  const expectedResult: Game = {
    blackToMove: false,
    moveHistory: ["e6", "f4", "e3", "f6", "g5", "d6", "e7", "f5", "c5"],
    board: [
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "B",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "B",
      "B",
      "B",
      "-",
      "-",
      "-",
      "-",
      "B",
      "B",
      "B",
      "B",
      "B",
      "-",
      "-",
      "-",
      "-",
      "B",
      "B",
      "B",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "B",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
      "-",
    ] as Board<Piece>,
  };
  assertEquals(finalState, expectedResult, "othello test");
});
